name: 'better'
description: 'An AI powered code review tool'
inputs:
  repo-token:  # id of input
    description: 'The repo token'
    required: true
  testInput:
    description: 'test input'
outputs:
  time: # id of output
    description: 'workflow ran'
runs:
  using: 'node20'
  main: 'dist/index.js'
